image: maven:3.8-openjdk-21
default:
  tags:
    - win10
stages:
  - test
Integration tests with Allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
  artifacts:
    paths:
      - build/reports/tests/*